name: build container image

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/ci-build-container-image.yml'
      - 'backend/**'
      - 'frontend/**'
      - '.dockerignore'
      - 'docker-init.sh'
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/ci-build-container-image.yml'
      - 'backend/**'
      - 'frontend/**'
      - '.dockerignore'
      - 'docker-init.sh'
      - 'Dockerfile'

jobs:

  build:
    name: Build container image on ubuntu
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: build docker image
      run: docker build --build-arg SKIP_BACKEND_TEST=true --build-arg SKIP_FRONTEND_TEST=true --build-arg CI=github .
