name: test_frontend

on:
  push:
    branches: [ master ]
    tags:
    paths:
      - '.github/workflows/ci-test-frontend.yml'
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/ci-test-frontend.yml'
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - run: npm ci
        working-directory: ./frontend

      - run: npx run-p check lint lint:style test
        working-directory: ./frontend

      - run: npm run size
        working-directory: ./frontend

      - run: npm run check:translation
        working-directory: ./frontend
